version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "1080:1080"
      - "1025:1025"
###< symfony/mailer ###
